### ISSUE TITLE
Keep it coming!!

### ISSUE THREAD

**Issue by HDking** [alex9311/Information-Retrieval#3]
I like what has been started! Thanks Alex. 

Please add all the stuff that comes into mind to be able and continnue on stuff on Monday. 
We are enthousiastic so far about the idea, but are falling behind. 

Wednesday the pitch is taking place (graded). Peter has said he wanted to do the pitch. But we need to be fully prepared to set up a non-shaky plan etc to be able to answer all questions.

**Comment by alex9311** [comment]
Yes I agree! We have our meeting monday where we can solidify our design.

Peter and I were discussing on what platform we should develop on. We discussed maybe trying to make an android app for this. What does everyone think?

**Comment by millenniumproof** [comment]
I was actually thinking of a web site with responsive/adaptive design so 
that it's easily accessible from a lot of different devices.

alex9311 schreef op 20-2-2015 om 13:23:

**Comment by PetervB** [comment]
I'm currently @ work, but I think developing an app for android enables us to use build in functions for phones while building an web site makes it harder to upload pictures from phones and that kind of stuff (should still be possible).

(I have practically no experience with designing android apps and web sites....)

**Comment by millenniumproof** [comment]
Shouldn't be a problem.

http://stackoverflow.com/questions/9398869/build-a-website-which-allows-image-video-submissions-via-smartphone

-Miriam

PetervB schreef op 20-2-2015 om 15:41:

**Comment by PetervB** [comment]
Cool!

**Comment by alex9311** [comment]
We should play to our strengths! That way we dont have to deal with much of a learning curve when developing. 

For web development I'm pretty comfortable developing in php and javascript (specifically the ExtJS library: http://dev.sencha.com/ext/5.1.0/examples/index.html), with MySQL DB. I have a little experience with android development, ruby on rails, and wordpress setups.

I know Peter is a solid Java programmer (android development is in JAVA) but has no experience in making android apps. Anything else Peter?

What are you guys good at?

**Comment by millenniumproof** [comment]
My strengths are actually in C# and C++ programming but I have some experience with Python and Javascript. I'm a fast learner either way. This is the only course I'm following this quarter (and a bit of freelance work on the side), so I have the time. I'll work on the Project Idea document for a bit tomorrow morning (^-^)b

**Comment by PetervB** [comment]
I'm an experienced java programmer and hove some experience in other languages. I tend to be able to pick up languages similar to java quite easy (due how you have to think about them)

**Comment by HDking** [comment]
I can work on the front-end stuff/ mock-ups etc.  Not experienced on Android though. 
For the rest, as the teacher mentioned, I should be focusing on the business side of things. 

I like the Android idea but not sure if we should do it.. you know, learning curve wise ;)

**Comment by millenniumproof** [comment]
The professor made a announcement on Blackboard. We have to send a pdf of the presentation to him and reserve a 5 min timeslot with Doodle. Hao and Peter, can you take care of this?

**Comment by PetervB** [comment]
Yeah, I'll handle it.

Hate this prof, using blackboard announcements, I always miss those...

**Comment by PetervB** [comment]
Reserved timeslot, finishing the slides/pitch

**Comment by millenniumproof** [comment]
By the way, the slides look good! It really looks like a proper business plan now. :)
