### ISSUE TITLE
Who is turning this in?

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#32]
Who is turning this in?

**Comment by millenniumproof** [comment]
I could make a pdf and send it in.

**Comment by millenniumproof** [comment]
Apparently we got an extension on the deadline. We'll add the finishing touches after class then. Like adding the logo to the front page :)

Dear students

as pointed out by some colleagues of yours, there was a bit of confusion as for the deadline of submission of the Project Idea Document, which I now extended to today March 4th at 23.59. 

Regards

Alessandro

**Comment by HDking** [comment]
we found out yesterday as well ;)

Who is available today to go through it critically and hand it in?

2015-03-04 6:59 GMT+01:00 millenniumproof notifications@github.com:

> Apparently we got an extension on the deadline.
> 
> Dear students
> 
> as pointed out by some colleagues of yours, there was a bit of confusion
> as for the deadline of submission of the Project Idea Document, which I now
> extended to today March 4th at 23.59.
> 
> Regards
> 
> Alessandro
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/32#issuecomment-77101714
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by millenniumproof** [comment]
I'm going to reformat the document and upload the pdf to github before 18:00.

Hao, can you upload a nice image of our logo for the front page?

**Comment by HDking** [comment]
it can be merged ;)

**Comment by millenniumproof** [comment]
Thanks! Can I also get non blurry versions of the latest goal tree and task tree?

**Comment by HDking** [comment]
they are not blurry at my computer.. Ill send you the ppts per email, then
you can safe them as jpg or pdf

2015-03-04 16:27 GMT+01:00 millenniumproof notifications@github.com:

> Thanks! Can I also get non blurry versions of the latest goal tree and
> task tree?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/32#issuecomment-77178169
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by millenniumproof** [comment]
Uhmm, how do I add a pdf file to Github.

**Comment by alex9311** [comment]
I think the only way to do it is through the console.

I can do it if you email it to me

**Comment by millenniumproof** [comment]
I did something. Haha. It should be in the documents folder. I merged the introduction with another piece so there's less overlap. Other than that, the most important parts of the document fit exactly on 5 pages (minus the diagrams) :D

**Comment by PetervB** [comment]
Looks good!

**Comment by alex9311** [comment]
looks great!

**Comment by millenniumproof** [comment]
I'm very proud I found a way to do the squiggly 'c' for Gizem's name. :D

**Comment by GizKockesen** [comment]
Hahahha thanks! Looks great :)

**Comment by millenniumproof** [comment]
The only thing really missing is the research sources. So if anyone has any ideas for that, post it here.

**Comment by HDking** [comment]
It really looks great!

**Comment by millenniumproof** [comment]
I added two sources just to have something. Last chance to comment on the document. At 22:30 I'm sending it in.

**Comment by alex9311** [comment]
thanks for adding that! Hopefully it boosts our grade even more. Looks great to me

**Comment by GizKockesen** [comment]
Yeah it looks great to me too :)

**Comment by millenniumproof** [comment]
I have submitted the document =(o^-^o)=

**Comment by HDking** [comment]
GREAT!!! looks amazing

2015-03-04 22:42 GMT+01:00 millenniumproof notifications@github.com:

> ```
>                                              \ \  / /
> ```
> 
> I have submitted the document =(o^-^o)=
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/32#issuecomment-77255633
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204
