### ISSUE TITLE
Meeting week 5

### ISSUE THREAD

**Issue by HDking** [alex9311/Information-Retrieval#34]
To keep it central. 

The idea was to have a meeting this week. I hear Wednesday as a preference from Peter. 
For me after Information Retrieval would be fine. Anybody conflicts in their agenda with this?

**Comment by millenniumproof** [comment]
Fine by me.

**Comment by alex9311** [comment]
Yep, Wednesday after lecture until 13:30 or after 15:30

**Comment by HDking** [comment]
Both of the suggestions work for me.. I think for this meeting we just need some alignment and off we go right? **So I think until 13.30 is good enough?**

**Comment by PetervB** [comment]
Sounds good, wednesday after lecture!
