### ISSUE TITLE
Scope discussion

### ISSUE THREAD

**Issue by HDking** [alex9311/Information-Retrieval#39]
#### Need
- [x] Submission page --> Gizem
  - [x] connection of submission page to DB -Alex
- [x] Image uploading --> Alex
- [x] Voting Page --> Hao
- [ ] Apache Solr (Lucene) Framework --> Peter
- [x] CrowdFlower integration --> Miriam
- [ ] Testing.. Sanity --> Miriam
#### Nice
- Log in/Sign in
- Swiping
- Admin Interface
- Success stories

**Comment by millenniumproof** [comment]
You make it look like I need to test my sanity! My brain is perfectly fine, thank you :P

**Comment by HDking** [comment]
haha sorry!

**Comment by alex9311** [comment]
How is everyone doing on this stuff?

**Comment by millenniumproof** [comment]
I have the code for mysql to csv for crowdflower and csv to mysql for the sanitation check part. Haven't tested it on the server yet though.

There is also a way to dynamically add data to a job on CrowdFlower and receive the results using JSON. I want to try and get that to work but I might not have the time today.

**Comment by PetervB** [comment]
I have put quite some time in lucene this weekend, I got to the part where I am using the MoreLikeThis method of lucene that is used to find similar documents, however this is currently only finding directly the same documents and I don't know why...

**Comment by HDking** [comment]
I've tried to learn it all myself, but I need some help from someone who
knows some stuff about PHP and SQL stuff to get the voting page work.

2015-03-15 16:17 GMT+01:00 PetervB notifications@github.com:

> I have put quite some time in lucene this weekend, I got to the part where
> I am using the MoreLikeThis method of lucene that is used to find similar
> documents, however this is currently only finding directly the same
> documents and I don't know why...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/39#issuecomment-81085697
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by millenniumproof** [comment]
Whoops. Committed to the Master. The Crowdflower stuff is in separate files anyway, so it's okay (^-^). I couldn't get it to work dynamically. I tried out stuff with cURL requests but I couldn't get a response. I can still look into it some more but I think the Similarity check (and even the FaceBook login) have higher priority because the user is not involved in the CrowdFlower part and it works the way it is now (just a bit of a pain in the ass to do the uploading and downloading manually).
