### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#4]
There are already several initiatives with the name IdeaTree, so if anyone has any other ideas post them here. Think along the line of growth, ideas, sparks of inspiration etc.

**Comment by alex9311** [comment]
GrowingSparks
IdeaGrow
StartSpark
SparkStart

anything sound good?

**Comment by millenniumproof** [comment]
I kinda like SparkStarter (haha, googled it and it's a matchmaking site). 
InSpark - Combining spark and inspire
Spurt - As in growth spurt

Coming up with names is hard. I guess it's okay to have a name similar to some other company as long as the concept is different enough.

**Comment by GizKockesen** [comment]
InSpark sounds cool. These are the ones that I can come up with for now:

IdeaBook (like Facebook but for ideas :P)
IdeaFeeder
IdeaSource

**Comment by millenniumproof** [comment]
I like IdeaFeeder. Fatting it up till we process it and make delicious bacon, haha.

**Comment by PetervB** [comment]
Sparked
- Your idea sparked into life -

(yes there are several other things that use this name, I still liked it :P )
