### ISSUE TITLE
Midterm presentation

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#42]
We have to reserve a slot on doodle for the midterm presentation with professor Bozzon.
http://doodle.com/g4i74kwmn9suviuw

How about we take the wednesday 15:00-15:30 slot?

**Comment by alex9311** [comment]
Thats not ideal for me, I have class until 3:30 and a TA meeting right after.

After 17:00 Wednesday would work for me but that might be super inconvenient for Gizem.

**Comment by GizKockesen** [comment]
If there is no other option then that's alright. I'll work and do some
sightseeing in delft maybe :)

**Comment by PetervB** [comment]
17:00 works for me 2

**Comment by HDking** [comment]
for me as well

**Comment by millenniumproof** [comment]
Ok, I reserved the 17:00-17:30 slot on next wednesday. If the weather's nice, I'll come along with the sightseeing, Gizem :D

**Comment by GizKockesen** [comment]
Yaayy hopefully it will be sunny!

**Comment by alex9311** [comment]
working on slides for the presentation here:
https://docs.google.com/presentation/d/10pcZMUSBqkkBA0lr6eLrcZD2CVG1O5BMSxzEhicU5I4/edit?usp=sharing
