### ISSUE TITLE
Dandelion and Lucene

### ISSUE THREAD

**Issue by PetervB** [alex9311/Information-Retrieval#47]
Hi All,

I'm still working on similarity search using Lucene, I can make index and tokens of the description however I can't figure out how to get it to do an actual similarity check.

I don't really have any clue left on how to get this to work...

Maybe someone can take a look at this with me?

**Comment by millenniumproof** [comment]
Since Gizem and Alex are looking into getting a webcrawler running I'll go and have a look at Lucene and Solr over the next days next to the CrowdFlower stuff. I'll let you know if I figure out anything.

**Comment by millenniumproof** [comment]
Did you already write a script to add the webcrawler results to Lucene. If not, I can write it.

**Comment by GizKockesen** [comment]
If solr is not working, maybe we can look at other alternatives in
parallel. I can check out dandelion again or I've read about rapidminer
which can also be used for calculating similarity and it works with mysql
as well. I don't know if it's good but maybe I can check it out to see if
it's better?

**Comment by millenniumproof** [comment]
Here's the php code to add csv results from the webcrawler to Solr. Just need to change the url and the filename. I'm still trying to understand the ranking and how to get the data we want.

```
    $filename = "Links2.csv";
$handle = fopen($filename, "r");
$XPost = fread($handle, filesize($filename));
fclose($handle);
$url = "http://localhost:8983/solr/Test/update";
$params = "?commit=true&fieldnames=Title,Developer,Description,Price,Category,Size,Dev,Rating,Nr_Ratings,Url"
$headers = array('Content-Type: application/csv');
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $XPost);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
curl_close($ch);*
```

**Comment by millenniumproof** [comment]
Performing a normal search query with the text description returns a ranking of similar results which seems pretty accurate. Not getting any similarity value or anything though. We can grab the top 5 and make a CrowdFlower job for confirmation like the original idea was. It's not exactly the same as calculating document similarity, but it's better than nothing.

What more info do we want to get out of the data we have? One thing we could add, I think it came up in the meeting with the professor, that by looking at the description a user gives of his app, we can guess the category. We can implement that by making use of the facet value parameters returned by a query.

**Comment by GizKockesen** [comment]
Oh cool, so the similarity computing is working now? I tried out rapidminer
today and it looks like a good alternative but if lucene is working now
then we can use that :)

**Comment by alex9311** [comment]
@PetervB have you seen what Miriam has got here? 

I'm sortof unclear whats happening here. Miriam are you able to use the solr setup that Peter had start on? Sorry for being out of the loop :sweat:

**Comment by millenniumproof** [comment]
Nah, I started yesterday morning just trying stuff out, getting Lucene working. Testing with a local server. I'm not using a extension or library just straight up sending cURL request. It's technically not a similarity check just a search query that returns a ranking, but I think we can still use it. For example, we can search through the webcrawler results on the description a user submitted, calculate the facet field 'Category' for the first 20 results (Lucene can do this) and then guess that the facet field that comes on top is the category of the description given.

**Comment by PetervB** [comment]
I haven't had any time yesterday so didn't see it before just now.

Seems good what Miriam has but maybe not for similarity but it does seem nice for ranking!

Maybe we should consider the switch to rapidminer?

**Comment by millenniumproof** [comment]
I downloaded RapidMiner. It has a lot of options for sure, but how can we incorporate it dynamically in our project?

**Comment by GizKockesen** [comment]
Hmm I will look into that.

**Comment by millenniumproof** [comment]
If we're having trouble getting the similarity check integrated dynamically, maybe we can run the test set through RapidMiner, dandelion (currently trying to get it working using curl requests) and Lucene (search ranking, cause morelikethis isn't working, and locally so we don't have to put an extra server online). We can then compare and present the results in the final presentation.

**Comment by GizKockesen** [comment]
Apparently you can schedule rapidminer to run the analysis regularly so
maybe we can use that to check ideas every week or something. But if that
doesn't work then we can do what you suggested, that's a good solution :)

**Comment by millenniumproof** [comment]
Looks like it will be difficult to get an instant similarity check. How are we going to incorporate that into the design? Do we still want to use it to accept/reject ideas if it means the user will have to wait a while till he hears if the idea is accepted or not? CrowdFlower isn't instantaneous either so it might be ok. Depending on the accuracy of the similarity check, we probably need a human to double check as well. How will we present the results to the user?

**Comment by GizKockesen** [comment]
I think the user will have to wait a bit until their idea gets accepted in
any case. Most platforms that need user content moderation require the user
to wait before having it posted on the platform, so I think people are used
to that idea.

In terms of presenting results, maybe the user can get a notification on
their profiles?

**Comment by millenniumproof** [comment]
I guess we would give a link to the idea in the system that was deemed the same or too similar so that the user can see what he should change when submitting an idea again.

Will we also check similarity with the webcrawler results? Or maybe just use the webcrawler results on the highest voted ideas to see what the market for the concept looks like and how to differentiate more from what's available.

**Comment by GizKockesen** [comment]
Yeah that works :)

I think we should use the webcrawler results since he asked for that in the
last meeting. But yeah we could just use it on the top ideas if that's
better.

**Comment by millenniumproof** [comment]
I got the similarity check with dandelion working using curl requests. Just have to write a script to process input and output. So if we want we can run the test set on both dandelion and rapidminer and compare the results.

**Comment by alex9311** [comment]
Thats awesome! Is it in master? So I guess now we have something for both human computation and IR working

**Comment by millenniumproof** [comment]
I had a look at whether I could implement the dandelion similarity check somewhat dynamically. Problem is you only get a limited amount of units (comparisons) per day, and looking at the price plans dandelion has, it's not feasible at all. At least not when comparing new ideas to all previous submitted ideas. Can't even get the test data set through it in one day. I started making a similarity matrix of the test data anyway (will be done tomorrow or the day after) so we can still compare results with RapidMiner. If I have the similarity data I could make a page where you can give an idea_id and see the different rankings for the test set. So we can at least show that. Maybe add an admin button to accept or reject an idea.
