### ISSUE TITLE
Web Crawler

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#48]
We need to create a web crawler that looks through the app store or play store and gets data on all existing mobile applications

**Comment by millenniumproof** [comment]
I'll have a crack at making a web crawler as well when I'm done with the CrowdFlower stuff. We can compare results and discuss our progress here.

**Comment by GizKockesen** [comment]
Could this help?
http://blog.singhanuvrat.com/tech/crawl-itunes-appstore-to-get-list-of-all-apps

**Comment by alex9311** [comment]
Yes that will definitely help! I can take a look into this in the next few days

**Comment by GizKockesen** [comment]
Cool! I can try it out as well, it looks like I can get it to work. Then I
will have finally done something useful for this project! :P

**Comment by alex9311** [comment]
Sounds good, I glanced over the code and didn't see anything that was grabbing a "description" field. I may have missed it though. That will be important to add if its not there

**Comment by alex9311** [comment]
have you had any luck with this? I got it running and ran it over night but it errored out and I cant get the data out of the output.

**Comment by GizKockesen** [comment]
Yeah it's been working fine but now all of a sudden it gives an error and I
know there is nothing wrong with the code. I'm gonna try it later again,
maybe something is wrong  with the servers or something.

**Comment by GizKockesen** [comment]
Did you manage to get it to work again? I've been trying and it wasn't
working. Then I changed the dump file and it started to work again :) I
need to figure out how to get the details to be printed out and not just
the urls though. I can save the data onto a csv file but I haven't managed
to save more details about the apps other than just the urls. I'm gonna
keep working on it :)

**Comment by alex9311** [comment]
No I haven't yet, does it run super slowly on your machine as well? It takes hours for mine to get through all the apps. Let me know if you make progress! I've been looking into possible alternatives that can grab the description as well

**Comment by GizKockesen** [comment]
Yeah I think there are too many apps :S

**Comment by HDking** [comment]
It is possible to scope it down for the demo? for example just take the top 100 of [any topic] and limit our test set to this topic as well?

**Comment by alex9311** [comment]
Yeah I'm sure thats what we'll end up doing

**Comment by GizKockesen** [comment]
I'm trying out another crawler which seems to work better. You can also set
a limit on how many apps per category you want to get. But it retrieves all
info but the description so I'm trying to add that into the code as well.

**Comment by GizKockesen** [comment]
Did it! I added the lines for retrieving the description of the gathered
apps :D I will put the whole thing on github :)

**Comment by millenniumproof** [comment]
Awesome!

**Comment by HDking** [comment]
cool!

**Comment by millenniumproof** [comment]
Now that we have the data from the webcrawler, how are we going to use it? Alex, Gizem and me talked about it during lunch today. With 1.000.000+ apps in the iStore of widely varying quality you don't want to reject an idea because it is similar to something in the app store. Similarity is almost inevitable.

One idea we had was that when a user wants to submit an idea we show the user some similar apps from the iStore, to encourage the user to elaborate more on his idea and what is unique about it. This would be an extra step and thus lower usability, but we didn't have any other good ideas yet. So if anyone has any other ideas, they're welcome?
