### ISSUE TITLE
Bluemix

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#5]
Did anyone have a look at the mail the professor sent? He suggests the possibility of using IBM's Bluemix. Might be a good way to get our project online.

**Comment by alex9311** [comment]
Seems like to a good option! Has anyone set one up? I'm happy to give it a try

**Comment by millenniumproof** [comment]
Go ahead. It seems pretty useful.

**Comment by alex9311** [comment]
Ok I got bluemix going with a php web app skeleton just to test it. 
http://tud-ir-test1.eu-gb.mybluemix.net/
It was really easy, however the free trial is only 30 days. Is that enough time for us?

**Comment by alex9311** [comment]
These are the options you have for a web application setup with bluemix:
![screen shot 2015-02-21 at 5 20 33 pm](https://cloud.githubusercontent.com/assets/1326899/6314823/0f9d628a-b9ee-11e4-8682-cf1361e0cd0f.png)

**Comment by millenniumproof** [comment]
PHP is probably the way to go. Don't you think? I think I can get up to speed pretty fast learning PHP.

The professor said in his mail that he can give access to guest accounts if we need it. I think we can set up the submitting page and voting page pretty fast. And after that work out the text parsing, searching and ranking implementation.

**Comment by alex9311** [comment]
Sounds good! I dont have a lot of experience making beautiful PHP apps but we'll hack it out.

Ok so should we tell him we want to use bluemix?

Also, what was the name of the database we wanted to use? Selenium? (EDIT: its Lucene)

These are the databases they offer out of the box:

![screen shot 2015-02-21 at 5 45 20 pm](https://cloud.githubusercontent.com/assets/1326899/6314934/874e3978-b9f1-11e4-9e3a-12ab16fb67a5.png)

**Comment by millenniumproof** [comment]
I have some online courses for dynamic web development using PHP. Bought a bundle a while ago. So maybe I can implement the front-end with responsive web-design. Maybe have Gizem design it with nice visuals.

I'm not familiar with any databases other than mysql, so I don't really know what would be best.

**Comment by alex9311** [comment]
The database tool I was thinking of was Lucene. I dont know anything about it though, or how hard it is to get working in this bluemix environment. I think that was an important part of our technology though
