### ISSUE TITLE
My Contribution

### ISSUE THREAD

**Issue by HDking** [alex9311/Information-Retrieval#51]
I have had a conversation with the professor after the last meeting, and one of the things discussed was the contributions a SEPAM-IA student could make within such a project. His advise for me was to focus more on the contextual side of the application instead of the implementation. 

I also confront him with the fact that he told us that the final presentation should focus on the implementation and not on selling the application, but he said that he definitely wanted to see some contextual story around it as well. 

So I propose I do this by diving into the justification of our project: finding the numbers and the research justifications around what we do and why and what the opportunities and challenges are in this project. In this way we can back up our claims during the final presentation. 
Next to that I can already think about the final presentation (together with Peter?) and the story we want to tell. 

How does that sound to you?

**Comment by millenniumproof** [comment]
Sounds good to me! You can research the current state of the market, ie how many apps get added (sold) on a daily basis and elaborate on how we intend to stand out.

**Comment by HDking** [comment]
I also found very interesting stuff about idea generation through crowdsourcing vs professional teams!

**Comment by millenniumproof** [comment]
Yeah, I saw the paper link you put on github. Wish we had that source in the Project Idea Document. Ah well, we can use it in the presentation. :)

**Comment by PetervB** [comment]
Hey,

Sounds good! We can work on the final presentation together :)

**Comment by millenniumproof** [comment]
Are you familiar with 'App Annie'. It's an analytics platform for mobile apps. Maybe you can have a look at how they use data on mobile apps to generate revenue.

**Comment by HDking** [comment]
oeh that's interesting
