### ISSUE TITLE
Potential bottlenecks/dangers for our project?

### ISSUE THREAD

**Issue by HDking** [alex9311/Information-Retrieval#55]
been working on the context and stuff and thought off some bottlenecks/dangers for our project. If you have any, add them! Please comment if you think that one of these is not one. 

Here goes:
- So much applications on the platforms (competition is high)
- How to keep ideas secret? Will it become a race?
- Checking similarity with such a big range is kind off hard
- Next to that reaching a sufficient level of accuracy is difficult as well with similarity checking. The text analysis should be able to detect keywords and recognize synonyms. 
- How are we getting people involved?
- Sanity checking can become a expensive undertaking, how can we check if it is done correctly?

These need to be discussed in some way I guess?

**Comment by millenniumproof** [comment]
The problem concerning similarity is not only scalability. Reaching a sufficient level of accuracy is difficult as well. The text analysis should be able to detect keywords and recognize synonyms.

**Comment by HDking** [comment]
updated!
