### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#56]
Dear students

as the Doodle suggests no clear winner (both Tuesday and Wednesday received a comparable number of votes), I decided to organize the presentations as following. 

On Tuesday 7-4-2015, the Lecture Hall M is gereserveerd van 08:00 tot en met 13:00.
On Wednesday 8-4-2015, the Lecture hall Chip is gereserveerd van 08:00 tot en met 13:00.

Presentations will take place on both days. You can select in the following Doodle the time-slot you find more suitable.  http://doodle.com/dimvmpxq4p4tyc76

There have been concerns about my requirements of having all of you to attend both presentation sessions. I do understand that you have a busy schedule and other deadlines in the same days, so my only expectation is for you to attend the presentations that take place the same day as yours. However, I am confindent you will do your best to attend both sessions. 

Alessandro

**Comment by millenniumproof** [comment]
We need to pick a date and time. Anytime is fine by me.

**Comment by GizKockesen** [comment]
Oh god it's from 8 am :S So early! :P Any day/time works for me too.

**Comment by millenniumproof** [comment]
In the doodle it says from 9:00 to 12:00. I'm guessing the 8:00 is a typo.

**Comment by GizKockesen** [comment]
Oh yay! Haha

**Comment by PetervB** [comment]
Both are fine for me, but I would prefer Wednesday

**Comment by millenniumproof** [comment]
Shall I reserve a slot on wednesday then? Only two left.

**Comment by alex9311** [comment]
Yep, either works for me!

**Comment by millenniumproof** [comment]
Wednesday is okay for Hao as well so I reserved a slot for wednesday april 8th 11:00-11:30.

**Comment by GizKockesen** [comment]
Cool, thanks!!

**Comment by alex9311** [comment]
Are we meeting before the presentation? If so, when?

**Comment by PetervB** [comment]
Let's meet Monday then we have time to fix possible stuff on Tuesday.

**Comment by GizKockesen** [comment]
Yeah I agree, it's safer if that's okay with everyone.

**Comment by alex9311** [comment]
Yeah that works for me, im free all day.

**Comment by millenniumproof** [comment]
Safety first! Monday's fine by me.

**Comment by HDking** [comment]
ahh I just made arragements with my family in law (yes.. ) to come over on
Monday.
Are you guys also available on Sunday?

2015-04-03 19:43 GMT+02:00 millenniumproof notifications@github.com:

> Safety first! Monday's fine by me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/56#issuecomment-89372556
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by millenniumproof** [comment]
I'm fine with sunday. The library at the university is open everyday.

**Comment by GizKockesen** [comment]
I can be available online on Sunday but I can't come in :(

**Comment by alex9311** [comment]
Sunday works for me!

**Comment by HDking** [comment]
@PetervB is Sunday possible for you as well?

**Comment by PetervB** [comment]
Nope, I don't have any time on Sunday...

**Comment by PetervB** [comment]
Maybe we can do two meetings? One on Sunday and one on Monday so that everyone knows what to do?

It is a bit overkill but I don't really see another way...

**Comment by HDking** [comment]
mweh sounds like a pain.

Lets do it as follows:
- Tomorrow I will work hard on getting everything in the slides (with
  styling etc) - similar like the pitch presentation -- No meeting --
  Therefore I need everything that you would think would be nice in the
  presentation.
- Monday we can have a 1h meeting about the presentation and what else
  needs to be included and done // division of the parts. I will be remote.
- Practice on Tuesday?? optional.. but it helps to know when you are up ;)

2015-04-04 16:11 GMT+02:00 PetervB notifications@github.com:

> Maybe we can do two meetings? One on Sunday and one on Monday so that
> everyone knows what to do?
> 
> It is a bit overkill but I don't really see another way...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/56#issuecomment-89584733
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by HDking** [comment]
change of plans ;) we are meeting tomorrow xD

2015-04-04 17:29 GMT+02:00 Hao Dinh h.c.dinh1@gmail.com:

> mweh sounds like a pain.
> 
> Lets do it as follows:
> - Tomorrow I will work hard on getting everything in the slides (with
>   styling etc) - similar like the pitch presentation -- No meeting --
>   Therefore I need everything that you would think would be nice in the
>   presentation.
> - Monday we can have a 1h meeting about the presentation and what else
>   needs to be included and done // division of the parts. I will be remote.
> - Practice on Tuesday?? optional.. but it helps to know when you are up ;)
> 
> 2015-04-04 16:11 GMT+02:00 PetervB notifications@github.com:
> 
> > Maybe we can do two meetings? One on Sunday and one on Monday so that
> > everyone knows what to do?
> > 
> > It is a bit overkill but I don't really see another way...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/56#issuecomment-89584733
> > .
> 
> ## 
> 
> Hao Dinh
> Korvezeestraat 442
> 2628 DV, Delft
> +31651272204

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by GizKockesen** [comment]
I can't meet tomorrow but I'm free all day on Monday and Tuesday.

**Comment by GizKockesen** [comment]
I saw the updated presentation now, looks good! But it would be great if we
could go over it together so that everyone knows what they need to say etc.
It's 50% of our project grade so I wanna make sure I understand everything.
Can we meet tomorrow or Tuesday? Or we could do it over Skype if you guys
can't meet up.

**Comment by HDking** [comment]
I think that is definitely necessary. I am making the slides as we speak, about 15 meters away from Miriam and Alex who are slaying away Solr right now.  
The names etc on the parts we can discuss also later, what everyone prefers, this is just what we thought could work. 
For me tomorrow will not be possible, but I planned to attend maybe one or two presentations on Tuesday, just to get an idea of the style, questions etc. Maybe its a good idea to get together on Tuesday as well to practice the presentation a couple of times?

**Comment by GizKockesen** [comment]
Great! I'm good for any time on Tuesday :)

**Comment by PetervB** [comment]
Sure I'm available tomorrow and the day after

**Comment by HDking** [comment]
Guys, I've uploaded the powerpoint file in the final_presentation folder. Could you add the content you think should be in there?
