### ISSUE TITLE
Adding ideas without images

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#58]
Can't submit a idea without an image or with a image with a filename that has already been used. You get a 'Sorry, file already exists.' notice. The filename should be prefixed with the idea_id.

**Comment by alex9311** [comment]
Good idea, I'll get on this today!

**Comment by alex9311** [comment]
made the changes and pull requested here: https://github.com/alex9311/TUD-Information-Retrieval-Group-02/pull/59
