### ISSUE TITLE
Cleaning up the repo

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#64]
Hey all, particularly @millenniumproof and @GizKockesen since some of these files you might be working on

I'd like to clean up the repo a bit. 
1. Can everyone please delete their old branches that they are no longer using? (also @PetervB and @HDking )
https://github.com/alex9311/TUD-Information-Retrieval-Group-02/branches/all

2.The pages directory is getting a bit cluttered

These I will leave in:
**blank_subpage.php**
**idea.php**
**submit.php**
**vote.php**
**top_ideas.php**

I'm going to make a page_functions directory where I'm going to put
**submit_functions.php**
**vote_functions.php**
**top_ideas_functions.php**

I'm removing this (its mine and old)
**print_ideas_table.php**          

Could I move these files to a new directory app/crowdflower (is anyone working in these in their branch?)
**crowdflower_admin_page.php**
**GetJSONresultsCrowdFlower.php**

And move these to a new directory in the database section (is anyone working in these in their branch?) 
**send_ideas_from_csv_to_mysql.php** 
**send_ideas_from_mysql_to_csv.php**

**Comment by alex9311** [comment]
I made a pull request with these file changes here https://github.com/alex9311/TUD-Information-Retrieval-Group-02/pull/65

**Comment by millenniumproof** [comment]
I'm not using these scripts anymore. They can be deleted or used by/merged into the admin_page you're making:
crowdflower_admin_page.php
send_ideas_from_csv_to_mysql.php
send_ideas_from_mysql_to_csv.php

If you're moving 'GetJSONresultsCrowdFlower.php', post the new web url here so I can change the webhook in the CrowdFlower job.

**Comment by alex9311** [comment]
Ok will do!! 

What capabilities should the admin page have? Getting results from crowdflower using your script? Adding ideas and crowdflower results by csv?

**Comment by millenniumproof** [comment]
The 'GetJSONresultsCrowdFlower.php' works behind the scenes and can't/shouldn't be called from the admin page. 

For the 'send_ideas_from_csv_to_mysql.php' you have to download the results from CrowdFlower manually and then upload. Also the code needs to be fixed a bit.

I don't know what functionally we need. Ideally an admin page would have functionality to view and change everything in the database, but that is not really necessary. Just think about which function would be good to have for testing and in case of problems. Like downloading and uploading data to the database. Sending ideas to crowdflower in a batch like in the "send_ideas_from_mysql_to_crowdflower.php" script.

**Comment by alex9311** [comment]
when you say `The 'GetJSONresultsCrowdFlower.php' works behind the scenes and can't/shouldn't be called from the admin page.` do you mean can/should?

**Comment by millenniumproof** [comment]
No, that script is set up so that it dynamically behind the scenes parses json unit results sent by CrowdFlower (that's why crowdflower needs to know the url). It gets called by CrowdFlower every time a unit has been judged. Calling it from the admin page wouldn't do anything.

**Comment by alex9311** [comment]
ohhh ok, thanks! Makes sense

Did you get a chance to look at my pull request?

**Comment by alex9311** [comment]
@millenniumproof here is the URL for that crowdflower handle now:
http://54.93.120.201/alex/project/app/crowdflower/GetJSONresultsCrowdFlower.php

**Comment by millenniumproof** [comment]
Thanks, updated it. I saw that there are some ideas in the crowdflower job. Are they in the database or did you reset that again?

**Comment by alex9311** [comment]
I think I've reset it since then, currently when I run the repopulation script on my ideas.csv it makes fake entries in the crowdflower results table for them

**Comment by millenniumproof** [comment]
Alright. I set up a clean job again. Are you done testing? So we can send in real ideas.

Btw, the crowdflower_admin_page can be deleted if you don't need it anymore.

**Comment by alex9311** [comment]
Yeah i'm done resetting for today.

I was going to build an interface that lets you upload ideas from CSV that doesn't mock the crowdflower result data but I can do that without resetting the DB. 

And OK, thanks!
