### ISSUE TITLE
Let's send in ideas!

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#66]
Let's all send in some app ideas so we'll have a nice set for the presentation.

Submit ideas here:
http://52.28.9.7/alex/project/app/pages/submit.php

Approve your idea in the CrowdFlower job here:
https://tasks.crowdflower.com/channels/cf_internal/jobs/710019/work?secret=zedvALZMgDf69dDDW6BWwRjrZN%2BuW39%2B%2BzDT4vtbi0bK

**Comment by alex9311** [comment]
So these should be real mobile application ideas we have? rather than the fake ones I've been making

**Comment by millenniumproof** [comment]
Yes, it'll be better to show real ideas at the demonstration instead of dummies.

**Comment by alex9311** [comment]
Hey @millenniumproof,

I submitted an idea but I cant find it on crowdflower. Your link above brought me to the "blub" fish dating app, which worked great! I was able to approve it and see it show up on the voting page.

I think the link you supplied may have been to that specific job? Is there somewhere we can see all the jobs for Sparked?

Cheers,
Alex

**Comment by millenniumproof** [comment]
It all goes to the same job. It might be because I clicked on the link just now. I saw the barber helper idea but I didn't judge it.

**Comment by alex9311** [comment]
Huh weird, I get this if I go to the link now

![screen shot 2015-04-03 at 3 42 29 pm](https://cloud.githubusercontent.com/assets/1326899/6982925/1eccdfa2-da18-11e4-9a52-efc14a7b9207.png)

**Comment by millenniumproof** [comment]
Weird, I haven't set any restriction on the amount of work per worker.

**Comment by millenniumproof** [comment]
I think it was just that the job got assigned to me 'cause I clicked on it sooner. I approved the ideas now. If you add more ideas you should have access to judge again.
