### ISSUE TITLE
Are we using solr-5.0.0

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#68]
Hey all,

Our server is filling up and rather than expanding it I want to try and remove stuff thats taking up too much space.

The thing that stands out to me is the solr-5.0.0 directory in /var/www/html. Its taking up a huge amount of space. I'm pretty sure this is a remnant of when Peter tried to get Solr (Lucene) working. If I understand right, we're using lucene through curl requests not ( @millenniumproof ?) so we don't need this directory anymore as far as I know. Can anyone confirm before I delete it?

**Comment by millenniumproof** [comment]
I ran the simililarity check tests on Lucene locally and wrote instructions on how to do that.

We're not actually using Lucene anywhere in the application so I think you can remove it.

**Comment by alex9311** [comment]
ok, will do. I transferred a copy of it to my computer in case we end up needing it.

Closing the issue!
