### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#71]
Hey all, so we have to have a live demo when we present. I think we can easily show 
- how you can submit an idea
- show how the idea doesn't show up in the voting yet
- Show how we approve it on crowdflower
- show how once approved we can vote for it on our application

My question is what do we want to show for IR ? Is there some sort of front end I should build for this? I think this question is mostly for @millenniumproof and @GizKockesen

**Comment by millenniumproof** [comment]
We can go more in-depth into the test results. Show some examples on the dandelion web site. Or give a demo of the RapidMiner program. But since we don't have that much time to present and Lucene basically came out of the test as the best solution I don't know if we want to spend much time there.

**Comment by PetervB** [comment]
I think we want to show the IR but I don't know how we want to show it.

**Comment by GizKockesen** [comment]
We can quickly show screenshots and explain the results. Showing the
program would be very cool too but yeah we can maybe see if we can squeeze
it in. But I agree, we should definitely show the IR.

**Comment by alex9311** [comment]
wasnt the original plan to make the IR part of the flow of the program? Like make the idea go through some IR check in addition to the crowdflower check. Is that not possible with what you guys have been working on with RapidMiner or Lucene?

**Comment by PetervB** [comment]
![sparked-process-flow](https://cloud.githubusercontent.com/assets/1016873/6993044/6c114d3c-dae7-11e4-858b-366bfff627d0.PNG)

I updated this for my individual summary, maybe we can use this?

**Comment by alex9311** [comment]
I dont think describing the application is really part of the individual group report. But its a nice diagram!

I was asking specifically about the demo though. We need to demo the **full flow** of the application and I'm asking how we can include IR in that

**Comment by millenniumproof** [comment]
If you want to implement Lucene in the application you would need to:
1. Set up a Lucene database on the server
2. Code to send the ideas to the database. Code to send a query. An admin page to check the results
Number 2 I can do but number 1 I have no idea.

Btw, Peter, you misspelled similarity ;)

**Comment by alex9311** [comment]
Is that the easiest way we can get IR into our application's flow? If so, I can try to set up lucene on our server.

What about Dandelion or RapidMiner? 

Do you guys agree that this is important to try to integrate into the app?

**Comment by alex9311** [comment]
Like at the end of this thread: https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/47

Miriam you were talking about getting dandelion similarity checks working with curl requests? Could that be our IR in the application?

**Comment by millenniumproof** [comment]
I don't know about RapidMiner. I only had a quick look at the program.

With Dandelion you have to query each new ideas one by one with all the previous ideas in the database. It might work now we only have a few ideas but you soon run out of credits for the day. It's not scalable and not a good solution the application.

Lucene works fast and has the best results. We can look at the code together if we're meeting up tomorrow, but Peter probably knows more about Lucene than I do.

I agree that it is an important part of the app, but it's all very last minute to add things now.

**Comment by alex9311** [comment]
OK lets try to get it working tomorrow then. Peter is busy all day apparently tomorrow so we'll have to do it without him. I'll get lucene installed on the server again tonight (that was the solr thing I deleted a few days ago). 

what time are you free?

**Comment by millenniumproof** [comment]
Any time is fine really, but it's my sister's birthday so I'd prefer to be done by 4 o'clock.

**Comment by alex9311** [comment]
Ok, want to meet at 10:30? I think the library is the only place at the TU that is open right? Anyone else coming?

**Comment by HDking** [comment]
I can be there

2015-04-04 17:26 GMT+02:00 Alex Simes notifications@github.com:

> Ok, want to meet at 10:30? I think the library is the only place at the TU
> that is open right? Anyone else coming?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex9311/TUD-Information-Retrieval-Group-02/issues/71#issuecomment-89595267
> .

## 

Hao Dinh
Korvezeestraat 442
2628 DV, Delft
+31651272204

**Comment by millenniumproof** [comment]
10:30 is fine by me! Let's meet at the entrance to the library.

**Comment by alex9311** [comment]
sounds good :thumbsup:

**Comment by PetervB** [comment]
I'm going to try to be available in the evening tomorrow.

**Comment by millenniumproof** [comment]
btw, I used this site to learn about Solr: http://www.solrtutorial.com

**Comment by GizKockesen** [comment]
With rapidminer, you have to connect it to our database. The program in my
pull request now reads it from a csv file. So instead of reading it from a
csv file, you can read from a database.

**Comment by GizKockesen** [comment]
We should still talk about the similarity results though.
