### ISSUE TITLE
Progress on Lucene

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#75]
Hey all,

Made some more progress on Lucene today after our meeting. I've been working on the lucene branch.

I made a script that takes the csv files outputted by the itunes crawler and puts them into our solr database. 

I added a "check duplicates" button which checks the app (without submitting it) against all the itunes applications in our solr database. The solr database does not contain our applications, only the itunes ones. ( @millenniumproof I'm adding the new idea to solr, doing the query, then removing the idea)

It sortof works but I think there is still an issue with the the solr query. Can someone help me with that? It also considers itself as a similar idea, which we dont want.

Try it out here:
http://52.28.9.7/alex/project/app/pages/submit.php

**Comment by alex9311** [comment]
and please tell me if theres issues with accessing it, its probably errors with the server ports. I moved us to a bigger server with more space

**Comment by alex9311** [comment]
we also need to make it so it correctly detects if no similar apps are found, the current check doesnt work

**Comment by PetervB** [comment]
I updated the code a bit, it seems to work better now. I basically made a threshold so that ideas with a score below 1 don't get accepted as similar ideas

**Comment by millenniumproof** [comment]
Curl failed: Failed to connect to 52.28.44.51 port 8983: Connection refused

I never had it returned the id I gave it in the morelikethis results. Where can I find the files? I don't see them on Git.

A threshold of one seems high. Running the test set the scores were usually lower for relevant documents. Though I guess, maybe with longer pieces of text, like the webcrawler results, you get higher scores.

**Comment by millenniumproof** [comment]
Found the files. The branch didn't show up in my GitHub console.

**Comment by millenniumproof** [comment]
If you want to take the title into account as well you need to add it to the mlt.fl parameter.

mlt.fl=title,text_description

**Comment by PetervB** [comment]
6.0369525 is the score for a perfect match

I think adding the title is not really handy because it's about the description not the title of the app.

**Comment by PetervB** [comment]
I'm trying to fix a nooby mistake (I didn't add this to the get function but filtered afterwards, fixing that now. Not really getting there though, can't find my (probably stupid little) mistake.

**Comment by millenniumproof** [comment]
I disagree about the title thing. Titles are often very descriptive of the main function of the app, ie. 'Cut the Rope', 'Zombies, Run!', 'Marktplaats', and should be taken into account.

**Comment by alex9311** [comment]
:thumbsup: I agree the title should be taken into account

**Comment by millenniumproof** [comment]
When you do a query the data you get in $response["response"]["docs"]; is always exactly the idea you're querying. Remember the query starts with 'select?q=id:".$id." , The similar ideas are all in  $response["moreLikeThis"][$new_idea_id]["docs"]; 

function get_similar_results_table($similar_results,$new_idea_id){
      $similar_docs = $similar_results["response"]["docs"];  <--- REMOVE THIS PART
      $more_similar_docs = $similar_results["moreLikeThis"][$new_idea_id]["docs"];

If you change this and add a threshold to the score you should get the results you want.

**Comment by alex9311** [comment]
ohhhh this makes sense, so this will remove the identical match. Thanks miriam! I think peter is going to implement this

**Comment by millenniumproof** [comment]
Also the scores are calculated relatively so a hard threshold is not a perfect solution. 

Taken from the LuceneFAQ:
"I would not recommend doing this because absolute score values in Lucene
are not meaningful (e.g., scores are not directly comparable across
searches).  The ratio of a score to the highest score returned is
meaningful, but there is no absolute calibration for the highest score
returned, at least at present, so there is not a way to determine from
the scores what the quality of the result set is overall."

**Comment by PetervB** [comment]
Ah, I can imagine, but we do need to do something... because the lower ones are just not relevant

**Comment by millenniumproof** [comment]
"The ratio of a score to the highest score returned is
meaningful.."

Calculate the ratio and put a threshold on that.

**Comment by alex9311** [comment]
sounds good to me!

**Comment by millenniumproof** [comment]
Added ratio check to the Lucene branch. Gah, I'm having internet connection problems at home :/

**Comment by PetervB** [comment]
Cool, I was also working on it on my branch but I guess you beet me to it :O

**Comment by GizKockesen** [comment]
Oh nice! We're getting to use the web crawler results too, that's cool!
It's strange that the similarity scoring is different, it was between 0 and
1 on rapidminer.

**Comment by alex9311** [comment]
Miriam are you able to request stuff from the solr server? It has to be running for it to work. I'm currently not running it but Peter knows how to get it running as well

**Comment by millenniumproof** [comment]
Yeah, the requests I run from local host work fine.

Btw, in lucene_functions, why are you also adding and removing the idea from the SQL database?

**Comment by PetervB** [comment]
My pc is turned on and logged in so it is still running, I currently have a brunch though don't know when I'll be back.

**Comment by alex9311** [comment]
Hey Miriam,

The thought with adding and removing the idea from the SQL database was to try and keep the IDs consistent between lucene and mysql. I'm not really sure if it makes sense but this way there is always a matching ID in our database to lucene. It seemed to me that it would be safer this way if we had multiple people submitting ideas or checking ideas. 

We should decide if we want to permanently add ideas that users submit to the lucene DB. What do you think?

Also, I couldn't find the Angry Birds app in the itunes app data. @GizKockesen is this not a complete set? I'm worried if he asks us to test with a popular application.

**Comment by PetervB** [comment]
For the current implementation the "highest score" is used, is this the score that is gained when searching for the document itself? Or the "highest score" in the similar documents?

Because we want to compare to the document itself (I think), not to the highest in the similar documents. The current way seems to be compared to the highest score in similar documents looking at the results I get from running some tests. Can you confirm?

If we go for comparing to the documents itself we the isempty check isn't enough. We now filter on ratio after checking if your idea is unique, however if there are results but the ratio is to low your Idea is unique, in the current implementation that wouldn't show.

**Comment by alex9311** [comment]
Not really sure what you're trying to say, maybe we can discuss it in person with everyone tomorrow

**Comment by GizKockesen** [comment]
Did you go through the other files, because the webcrawler splits the
output into multiple files. But it is possible that it didn't get angry
birds because for it to gather all the apps it needs to run for hours and
hours. There are too many apps. But if we were to be releasing the app for
real, the crawler is indeed capable of gathering all the apps. It's just a
matter of how long you run it.

**Comment by PetervB** [comment]
I created the version I think we would like on my branch, lets discuss the ratio tomorrow in person.

**Comment by millenniumproof** [comment]
@PetervB I get where you're coming from. The way it is now doesn't take into account if the first result in similarity is not very similar. There is no way to compare a document to itself though. The moreLikeThis function excludes the document itself in its results. And I don't think it's the right way either. Looking at the results from the testset there is a wide range in scores for relevant documents. If you want to add an threshold for minimum score it would have to be in the 0.05-0.1 range.

**Comment by PetervB** [comment]
https://github.com/alex9311/TUD-Information-Retrieval-Group-02/blob/peterb-lucene/app/page_functions/lucene_functions.php

That does it the way I described (using the response instead of the most similar)

**Comment by millenniumproof** [comment]
@alex9311 Ah, I see. I was already wondering how you maintained id integrity. I thought that we would show the user only similar results from the submissions we got. The webcrawler results cause a bit of information overload cause the descriptions are not very good, succinct summaries of app functionality.

**Comment by millenniumproof** [comment]
@PetervB I don't think the score of the response is what you think it is. Are you sure of how that value is calculated? Because to me it just seems you ask for an id and receive the document attached to the id without any comparisons or term calculations. I may be wrong though.

**Comment by alex9311** [comment]
@GizKockesen yeah I think I got all the files, it was like Links1.csv through Links9.csv. Does that sound right?

@millenniumproof Yeah we'll have to discuss if we want to use the itunes data or not. I agree that it is information overload but I think the prof will be really happy if we show that we used it. Maybe if we fine tune the similarity query more it will handle it better?

**Comment by PetervB** [comment]
That could be, I'm not 100% sure what it is, I would expect it to be the score when running the query on the document itself (the 100% match), if this is not the case I guess we shouldn't use this.

**Comment by millenniumproof** [comment]
@PetervB I think it's just the score of the id number we give compared to the id number of the document it finds, because that's what you're asking in the query.

@alex9311 Yeah, I definitely admire the effort to incorporate the web crawler results. I'm just not sure it's a right fit how it's implemented now.

**Comment by GizKockesen** [comment]
Yeah that's all the files, in that case we will have to run it for a longer
time.

**Comment by PetervB** [comment]
@millenniumproof I guess then we want to go for the other solution, but then we might wan't to consider adding a threshold as you suggested to avoid matches that are not really similar.

**Comment by millenniumproof** [comment]
@PetervB Yeah, you can add an extra overall threshold, but like I said, don't set it too high.

**Comment by PetervB** [comment]
Will do :)

**Comment by PetervB** [comment]
I just ran some queries with the threshold but as you said it's not usefull as the highest score differs a lot per query...

**Comment by alex9311** [comment]
@millenniumproof I agree its a bit awkward. We should decide as a group tomorrow what to include in the solr database. I really do think the professor wanted to see us used the itunes data though
