### ISSUE TITLE
Mail by Bozzon

### ISSUE THREAD

**Issue by PetervB** [alex9311/Information-Retrieval#77]
Dear students

there are several important announcements that are posted on Blackboard. Unfortunately, there is something wrong with the BB email system, and such announcements were not communicated to you.

To make sure you receive all the information you need:

1) Have a look to the BB of the course, at least tonight and tomorrow early morning
2) Make sure that all your group members are aware of such communications. _NOT ALL OF YOU_ will receive this email (I listed only students with whom I had previous communication with), so _I RELY ON YOU COLLABORATION TO MAKE SURE THAT THIS MESSAGE REACHES ALL OF YOU_

As always, you can send me an email if you have further doubts.

See you all tomorrow and/or Wednesday

**Comment by HDking** [comment]
I've seen it :)

**Comment by alex9311** [comment]
Do we need to be at the presentations tomorrow?

**Comment by GizKockesen** [comment]
No we don't.

**Comment by PetervB** [comment]
Dear all

again, I am afraid BB mail might not be working fine. So, in case, this email is to let you know that today’s presentation will take place in the Dijkstrazaal (9th Floor, HB9.160). 

Please let your group members know

See you later

Alessandro

**Comment by PetervB** [comment]
Also we planned to meet at 14:00 today at drebbelweg
