### ISSUE TITLE
Feedback on individual Contributions

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#78]
@HDking @millenniumproof 

We were talking about this yesterday, not sure if you saw the blackboard announcement. The feedback we're supposed to give on each of our teammates is due with the individual report, not at a later date.

![screen shot 2015-04-06 at 4 24 15 pm](https://cloud.githubusercontent.com/assets/1326899/7005565/663c3046-dc79-11e4-9f4f-d4078882e32c.png)

**Comment by HDking** [comment]
ah ok! thanks Alex!
